In [258]:
#!/usr/bin/env python3
import sys, math, csv
import numpy as np
import matplotlib.pyplot


#xHidden = w_input_hidden * I matrix inputs

class NeuralNetwork:
    
    def __init__(self, inputNodes,hiddenNodes,outputNodes ):
        self.iNodes = inputNodes
        self.oNodes = outputNodes
        self.hNodes = hiddenNodes
        self.wInputHidden = np.random.rand(self.hNodes,self.iNodes)
        self.wOutput = np.random.rand(self.oNodes, self.hNodes)
        self.lr = 0.1

        
        self.learningRate = 0.5
    def printStats(self):
        print("number of inputs {}, hidden {}, output {}".format(self.iNodes, self.oNodes, self.hNodes))
        print("wInputHidden")
        print(self.wInputHidden)
        print("wOutput")
        print(self.wOutput)
    def train(self, inputs_list, targets_list):
        pass
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list).T
        
        # calculate signals into hidden layer
        hidden_inputs = np.dot(self.wInputHidden, inputs)
        print("input hidden")
        print(self.wInputHidden)
        
        
        # calculate the signals emerging from hidden layer
        hidden_outputs = [self.sigmoid(x) for x in hidden_inputs]
        hidden_outputs = np.array(hidden_outputs)
        print("hidden outputs")
        print(hidden_outputs)
        print("targets")
        
        print(targets)
        
        # calculate signals into final output layer
        final_inputs = np.dot(self.wOutput, hidden_outputs)
        print("final ouputs")
        
        # calculate the signals emerging from final output layer
        final_outputs = [self.sigmoid(x) for x in final_inputs]
        final_outputs = np.array(final_outputs)
        print(final_outputs)
        
        
        # output layer error is the (target - actual)
        output_errors = targets - final_outputs
        print("output errors")
        print(output_errors)
        
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = np.dot(self.wOutput.T, output_errors)
        print("Hidden ERRORS")
        print(hidden_errors)

        self.wOutput += self.lr * np.dot((output_errors * final_outputs * (1.0 - final_outputs)),np.transpose(hidden_outputs))
        
        
    def query(self, input_list):
        # Create numpy array with input list
        inputs = np.array(input_list, ndmin=0).T

        # calculate new hidden inputs from inputs and weights of input layer
        hidden_inputs = (np.dot(self.wInputHidden, inputs))
        # run middle layer through sigmoid
        siged_hidden_outputs = [self.sigmoid(x) for x in hidden_inputs ]
        # multiply outputs with output weights
        final_inputs = np.dot(self.wOutput, siged_hidden_outputs)
        # run last layer through sigmoid 
        siged_final_outputs = [self.sigmoid(x) for x in final_inputs]

        return siged_final_outputs

    def sigmoidPrime(self,x):
        return (self.sigmoid(x) - (1-self.sigmoid(x)))

    # sigmoid activation function
    def sigmoid(self,x):
        return 1 / (1 + math.exp(-x))


def main():
    newNN = NeuralNetwork(4, 5, 3)
    a = np.array([0,0,1,1])
    #newNN.printStats()
    bb = newNN.query(a)
    print(bb)
    inputsTest = np.array([4, 5, 6,8])
    outputTarget = [1,0,1]
    newNN.train(inputsTest, outputTarget)
    

In [259]:
if __name__ == '__main__':
    main()

[0.85035174807769, 0.754467837496458, 0.8837982269470965]
input hidden
[[0.56954069 0.62957179 0.05306736 0.77572617]
 [0.71106981 0.89858298 0.57024552 0.22933493]
 [0.77209074 0.12676147 0.78813583 0.30573724]
 [0.95602508 0.31727382 0.30684978 0.71134931]
 [0.72319268 0.98706367 0.96189217 0.82372032]]
hidden outputs
[0.99999354 0.99999661 0.99998148 0.99999761 1.        ]
targets
[1 0 1]
final ouputs
[0.91023202 0.82515815 0.93345791]
output errors
[ 0.08976798 -0.82515815  0.06654209]
Hidden ERRORS
[-0.56397019 -0.02815386 -0.28577433 -0.05625498  0.0374386 ]


ValueError: shapes (3,) and (5,) not aligned: 3 (dim 0) != 5 (dim 0)