In [53]:
#!/usr/bin/env python3
import sys, math, csv
import numpy as np
import matplotlib.pyplot
%matplotlib inline

#xHidden = w_input_hidden * I matrix inputs

class NeuralNetwork:
    
    def __init__(self, inputNodes,hiddenNodes,outputNodes ):
        self.iNodes = inputNodes
        self.oNodes = outputNodes
        self.hNodes = hiddenNodes
        self.wInputHidden = np.random.rand(self.hNodes,self.iNodes)
        self.wOutput = np.random.rand(self.oNodes, self.hNodes)
        self.learningRate = 1
        
        self.learningRate = 0.5
    def printStats(self):
        print("number of inputs {}, hidden {}, output {}".format(self.iNodes, self.oNodes, self.hNodes))
        print("wInputHidden")
        print(self.wInputHidden)
        print("wOutput")
        print(self.wOutput)
        
    def train(self):
        pass
    
    def query(self, input_list):
        # Create numpy array with input list
        inputs = np.array(input_list, ndmin=0).T
        print("inputs:")
        print(inputs)
        # calculate new hidden inputs from inputs and weights of input layer
        hidden_inputs = (np.dot(self.wInputHidden, inputs))
        print("hidden inputs after dot product")
        print(hidden_inputs)
        
        print("hidden Outputs after mult")
        siged_hidden_outputs = [self.sigmoid(x) for x in hidden_inputs ]
        print(hidden_inputs)
        print("hidden after sig")
        print(siged_hidden_outputs)
        
        final_inputs = np.dot(self.wOutput, siged_hidden_outputs)
        print("final_inputs")
        print(final_inputs)
        
        siged_final_outputs = [self.sigmoid(x) for x in final_inputs]
        print("siged final outputs")
        print(siged_final_outputs)

    def sigmoidPrime(self,x):
        return (self.sigmoid(x) - (1-self.sigmoid(x)))

    # sigmoid activation function
    def sigmoid(self,x):
        return 1 / (1 + math.exp(-x))


def main():
    newNN = NeuralNetwork(4, 5, 3)
    a = np.array([1,0,0,1])
    newNN.printStats()
    newNN.query(a)

    

In [54]:
if __name__ == '__main__':
    main()

number of inputs 4, hidden 3, output 5
wInputHidden
[[0.18768776 0.93966754 0.59965435 0.26630898]
 [0.71716099 0.54833916 0.50104872 0.45438892]
 [0.49881844 0.62586156 0.11469112 0.10706856]
 [0.16400201 0.21188383 0.66794056 0.97534732]
 [0.78212644 0.40384603 0.51948113 0.22715305]]
wOutput
[[0.68310596 0.06255215 0.07486091 0.91810802 0.23844969]
 [0.64515275 0.71156045 0.20427558 0.18630417 0.23717405]
 [0.71895244 0.67715922 0.28963879 0.23277948 0.24372581]]
hidden Outputs after mult
[0.45399675 1.17154991 0.605887   1.13934933 1.00927949]
hidden after sig
[0.611589074689745, 0.7634250545715364, 0.6470020006215393, 0.7575601546420316, 0.732879121560397]
final_inputs
[1.38424602 1.38491468 1.49902666]
siged final outputs
[0.7996720643028281, 0.7997791595999708, 0.8174292615532601]
