In [44]:
#!/usr/bin/env python3
import sys, math, csv
import numpy as np
import matplotlib.pyplot


#xHidden = w_input_hidden * I matrix inputs

class NeuralNetwork:
    
    def __init__(self, inputNodes,hiddenNodes,outputNodes ):
        self.iNodes = inputNodes
        self.oNodes = outputNodes
        self.hNodes = hiddenNodes
        self.wInputHidden = np.random.rand(self.hNodes,self.iNodes)
        self.wOutput = np.random.rand(self.oNodes, self.hNodes)
        self.lr = 0.1

        
        self.learningRate = 0.5
    def printStats(self):
        print("number of inputs {}, hidden {}, output {}".format(self.iNodes, self.oNodes, self.hNodes))
        print("wInputHidden")
        print(self.wInputHidden)
        print("wOutput")
        print(self.wOutput)
        
    def train(self, inputs_list, targets_list):
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T
        print("inputs")
        print(inputs)
        print("targets")
        print(targets)
       
        ############################# FIRST LAYER
        # calculate signals into hidden layer
        hidden_inputs = np.dot(self.wInputHidden, inputs)
        print("hidden_inputs")
        print(hidden_inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = np.array([self.sigmoid(x) for x in hidden_inputs])
        print("hidden outputs after sigmoid")
        print(hidden_outputs)
       
        # calculate signals into final output layer
        final_inputs = np.dot(self.wOutput, hidden_outputs)
        print("final inputs")
        print(final_inputs)
        # calculate the signals emerging from final output layer
        print("final_outputs")
        final_outputs = np.array([self.sigmoid(x) for x in final_inputs])
        print(final_outputs)
        
        ###########################################################
    
        # Calculate ERRORS at the ouput NODES
        output_errors = targets_list - final_outputs
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = np.dot(self.wOutput.T, output_errors)
       
        # update the weights for the links between the hidden and output layers
        #self.wInputHidden += self.lr * np.dot((output_errors * final_outputs * (1.0 - final_outputs)), np.transpose(hidden_outputs))

        
    def query(self, input_list):
        # Create numpy array with input list
        inputs = np.array(input_list, ndmin=0).T

        # calculate new hidden inputs from inputs and weights of input layer
        hidden_inputs = (np.dot(self.wInputHidden, inputs))
        # run middle layer through sigmoid
        siged_hidden_outputs = [self.sigmoid(x) for x in hidden_inputs ]
        # multiply outputs with output weights
        final_inputs = np.dot(self.wOutput, siged_hidden_outputs)
        # run last layer through sigmoid 
        siged_final_outputs = [self.sigmoid(x) for x in final_inputs]

        return siged_final_outputs

    def sigmoid(self, s):
    # activation function
        return 1/(1+np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)


def main():
    newNN = NeuralNetwork(4, 5, 3)
    a = np.array([0,0,1,1])
    #newNN.printStats()
    bb = newNN.query(a)
    print(bb)
    inputsTest = np.array([4, 5, 6, 8])
    outputTarget = [1,0,1]
    newNN.train(inputsTest, a)

In [45]:
if __name__ == '__main__':
    main()

[0.8743862106103767, 0.8336008201792762, 0.8976453289722294]
inputs
[[4]
 [5]
 [6]
 [8]]
targets
[[0]
 [0]
 [1]
 [1]]
hidden_inputs
[[16.26979254]
 [15.13367658]
 [ 9.19201975]
 [14.08131604]
 [15.74897687]]
hidden outputs after sigmoid
[[0.99999991]
 [0.99999973]
 [0.99989816]
 [0.99999923]
 [0.99999986]]
final inputs
[[2.55751308]
 [2.14817262]
 [2.79318156]]
final_outputs
[[0.92807663]
 [0.89549789]
 [0.94230625]]


ValueError: shapes (3,4) and (1,5) not aligned: 4 (dim 1) != 1 (dim 0)