In [24]:
#!/usr/bin/env python3
import sys, math, csv
import numpy as np
import matplotlib.pyplot


#xHidden = w_input_hidden * I matrix inputs

class NeuralNetwork:
    
    def __init__(self, inputNodes,hiddenNodes,outputNodes ):
        self.iNodes = inputNodes
        self.oNodes = outputNodes
        self.hNodes = hiddenNodes
        self.wInputHidden = np.random.rand(self.hNodes,self.iNodes)
        self.wOutput = np.random.rand(self.oNodes, self.hNodes)
        self.lr = 0.1

        
        self.learningRate = 0.5
    def printStats(self):
        print("number of inputs {}, hidden {}, output {}".format(self.iNodes, self.oNodes, self.hNodes))
        print("wInputHidden")
        print(self.wInputHidden)
        print("wOutput")
        print(self.wOutput)
        
    def train(self, inputs_list, targets_list):
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T
        print("inputs")
        print(inputs)
        print("targets")
        print(targets)
       
        ############################# FIRST LAYER
        # calculate signals into hidden layer
        hidden_inputs = np.dot(self.wInputHidden, inputs)
        print("hidden_inputs")
        print(hidden_inputs)
        print("shape of hidden inputs",hidden_inputs.shape)
        # calculate the signals emerging from hidden layer
        hidden_outputs = np.array([self.sigmoid(x) for x in hidden_inputs])
        print("hidden outputs after sigmoid")
        print(hidden_outputs)
        print("shape of hidden outputs ",hidden_outputs.shape)
        
           
        ############################ SECOND LAYER    
        # calculate signals into final output layer
        final_inputs = np.dot(self.wOutput, hidden_outputs)
        print("final inputs")
        print(final_inputs)
        print("final inputs", final_inputs.shape)
        # calculate the signals emerging from final output layer
        print("final_outputs")
        final_outputs = np.asarray([self.sigmoid(x) for x in final_inputs])
        print(final_outputs)
        print("final outputs shape", final_outputs.shape)
        
        ################################ ERRORS
    
        # Calculate ERRORS at the ouput NODES
        #output_errors = targets_list - final_outputs
        output_errors = np.array(targets - final_outputs, ndmin=2)
        print("output Errors")
        print(output_errors)
        print("output error shape",output_errors.shape)
        
        ################## BackPropagation STEPS
        
        outputErrorDerived = output_errors * final_outputs * (1.0 - final_outputs)
        
        print("output Error Derived")
        print(outputErrorDerived)
        print("output error shape ", outputErrorDerived.shape)
        
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = np.dot(self.wOutput.T, output_errors)
        print("hidden errors")
        print(hidden_errors)
        print("hidden errors shape", hidden_errors.shape)
       
        print("final outputs")
        print(final_outputs)
        print("final outputs shape", final_outputs.shape)
    
        print("input hidden weights")
        print(self.wInputHidden)
        print("weights input hidden layer", self.wInputHidden.shape)
        
        print("output weights")
        print(self.wOutput)
        print("weights output layer", self.wOutput.shape)
        # update the weights for the links between the hidden and output layers
        self.wOutput += self.lr * np.dot((outputErrorDerived), np.transpose(hidden_outputs))
        print("output error derived", outputErrorDerived)
        print("wOutput", self.wOutput)
        
        print("input weights before", self.wInputHidden)
        self.wInputHidden += self.lr * np.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), np.transpose(inputs))
        print("input weights before", self.wInputHidden)
        
    def query(self, input_list):
        # Create numpy array with input list
        inputs = np.array(input_list).T

        # calculate new hidden inputs from inputs and weights of input layer
        hidden_inputs = (np.dot(self.wInputHidden, inputs))
        # run middle layer through sigmoid
        siged_hidden_outputs = [self.sigmoid(x) for x in hidden_inputs ]
        # multiply outputs with output weights
        final_inputs = np.dot(self.wOutput, siged_hidden_outputs)
        # run last layer through sigmoid 
        siged_final_outputs = [self.sigmoid(x) for x in final_inputs]

        return siged_final_outputs

    def sigmoid(self, s):
    # activation function
        return 1/(1+np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)


def main():
    newNN = NeuralNetwork(4, 5, 3)
    a = np.array([0,0,1,1])
    #newNN.printStats()
    bb = newNN.query(a)
    print(bb)
    inputsTest = np.array([4, 5, 6, 8])
    outputTarget = [1,0,1]
    newNN.train(inputsTest, outputTarget)

In [25]:
if __name__ == '__main__':
    main()

[0.8754417734777055, 0.915026527079764, 0.9035087830078178]
inputs
[[4]
 [5]
 [6]
 [8]]
targets
[[1]
 [0]
 [1]]
hidden_inputs
[[11.23433277]
 [12.33925113]
 [14.34632956]
 [ 5.21783258]
 [ 8.49111673]]
shape of hidden inputs (5, 1)
hidden outputs after sigmoid
[[0.99998679]
 [0.99999562]
 [0.99999941]
 [0.99461015]
 [0.99979476]]
shape of hidden outputs  (5, 1)
final inputs
[[2.75036068]
 [3.4012367 ]
 [3.23002445]]
final inputs (3, 1)
final_outputs
[[0.93993372]
 [0.96774316]
 [0.96194865]]
final outputs shape (3, 1)
output Errors
[[ 0.06006628]
 [-0.96774316]
 [ 0.03805135]]
output error shape (3, 1)
output Error Derived
[[ 0.00339124]
 [-0.03020939]
 [ 0.00139281]]
output error shape  (3, 1)
hidden errors
[[-0.59870065]
 [-0.17259122]
 [-0.89499707]
 [-0.60166942]
 [-0.73885821]]
hidden errors shape (5, 1)
final outputs
[[0.93993372]
 [0.96774316]
 [0.96194865]]
final outputs shape (3, 1)
input hidden weights
[[0.70807673 0.33819465 0.0475239  0.80323865]
 [0.05627609 0.98310337 0.9

In [26]:
x = np.array([[1, 2, 3]])

x.T
x.shape

(1, 3)