In [70]:
#!/usr/bin/env python3
import sys, math, csv
import numpy as np
import matplotlib.pyplot


#xHidden = w_input_hidden * I matrix inputs

class NeuralNetwork:
    
    def __init__(self, inputNodes,hiddenNodes,outputNodes ):
        self.iNodes = inputNodes
        self.oNodes = outputNodes
        self.hNodes = hiddenNodes
        self.wInputHidden = np.random.rand(self.hNodes,self.iNodes)
        self.wOutput = np.random.rand(self.oNodes, self.hNodes)
        self.lr = 0.1

        
        self.learningRate = 0.5
    def printStats(self):
        print("number of inputs {}, hidden {}, output {}".format(self.iNodes, self.oNodes, self.hNodes))
        print("wInputHidden")
        print(self.wInputHidden)
        print("wOutput")
        print(self.wOutput)
        
    def train(self, inputs_list, targets_list):
        # convert inputs list to 2d array
        inputs = np.array(inputs_list).T
        targets = np.array(targets_list).T
        print("inputs")
        print(inputs)
        print("targets")
        print(targets)
       
        ############################# FIRST LAYER
        # calculate signals into hidden layer
        hidden_inputs = np.dot(self.wInputHidden, inputs)
        print("hidden_inputs")
        print(hidden_inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = np.array([self.sigmoid(x) for x in hidden_inputs])
        print("hidden outputs after sigmoid")
        print(hidden_outputs)
           
        ############################ SECOND LAYER    
        # calculate signals into final output layer
        final_inputs = np.dot(self.wOutput, hidden_outputs)
        print("final inputs")
        print(final_inputs)
        # calculate the signals emerging from final output layer
        print("final_outputs")
        final_outputs = np.array([self.sigmoid(x) for x in final_inputs])
        print(final_outputs)
        
        ################################ ERRORS
    
        # Calculate ERRORS at the ouput NODES
        #output_errors = targets_list - final_outputs
        output_errors = np.subtract(targets_list, final_outputs)
        print("output Errors")
        print(output_errors)
        
        ################## BackPropagation STEPS
        
        outputErrorDerived = output_errors * final_outputs * (1.0 - final_outputs)
        print("output Error Derived")
        print(outputErrorDerived)
        
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = np.dot(self.wOutput.T, output_errors)
        print("hidden errors")
        print(hidden_errors)
       
        print("final outputs")
        print(final_outputs)
    
        print("input hidden weights")
        print(self.wInputHidden)
        
        print
        # update the weights for the links between the hidden and output layers
        #self.wInputHidden += self.lr * np.dot((output_errors * final_outputs * (1.0 - final_outputs)), np.transpose(hidden_outputs))

        
    def query(self, input_list):
        # Create numpy array with input list
        inputs = np.array(input_list, ndmin=0).T

        # calculate new hidden inputs from inputs and weights of input layer
        hidden_inputs = (np.dot(self.wInputHidden, inputs))
        # run middle layer through sigmoid
        siged_hidden_outputs = [self.sigmoid(x) for x in hidden_inputs ]
        # multiply outputs with output weights
        final_inputs = np.dot(self.wOutput, siged_hidden_outputs)
        # run last layer through sigmoid 
        siged_final_outputs = [self.sigmoid(x) for x in final_inputs]

        return siged_final_outputs

    def sigmoid(self, s):
    # activation function
        return 1/(1+np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)


def main():
    newNN = NeuralNetwork(4, 5, 3)
    a = np.array([0,0,1,1])
    #newNN.printStats()
    bb = newNN.query(a)
    print(bb)
    inputsTest = np.array([4, 5, 6, 8])
    outputTarget = [1,0,1]
    newNN.train(inputsTest, outputTarget)

In [71]:
if __name__ == '__main__':
    main()

[0.9513188002806963, 0.9372317965246484, 0.7572153924539404]
inputs
[4 5 6 8]
targets
[1 0 1]
hidden_inputs
[16.59930541 16.93197511  9.73698283  7.75186663 17.92169988]
hidden outputs after sigmoid
[0.99999994 0.99999996 0.99994095 0.99957025 0.99999998]
final inputs
[3.85782139 3.45851041 1.47534308]
final_outputs
[0.97932263 0.96948393 0.81386815]
output Errors
[ 0.02067737 -0.96948393  0.18613185]
output Error Derived
[ 0.00041871 -0.02868203  0.02819652]
hidden errors
[-0.72806159 -0.46147818 -0.15660015 -0.74248408 -0.91029674]
final outputs
[0.97932263 0.96948393 0.81386815]
input hidden weights
[[0.56489467 0.68397459 0.80966596 0.75773225]
 [0.54608391 0.83238384 0.842229   0.69154328]
 [0.10656344 0.79676601 0.36495415 0.39214676]
 [0.17356749 0.76710101 0.51378291 0.01742428]
 [0.86506653 0.23823662 0.9550642  0.94248318]]
